import  { useState, useEffect } from 'react';

const Counts = () => {
    const [counter, setCounter] = useState(0);

    useEffect(() => {
        const interval = setInterval(() => {
            setCounter((prev) => {
                if (prev >= 100) {
                    clearInterval(interval);
                    return prev; 
                }
                return prev + 1;
            });
        }, 100);

        return () => clearInterval(interval); 
    }, []);

    return (
        <div className="bg-gray-50 p-8 min-h-[350px] flex flex-col items-center justify-center font-sans">
            <h2 className="text-blue-600 text-3xl font-bold mb-16 text-center">Application Metrics</h2>
            <div className="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12">
                <div className="text-center">
                    <h3 className="text-gray-800 text-4xl font-extrabold">{counter}<span className="text-blue-600">M+</span></h3>
                    <p className="text-base font-bold mt-4">Total Users</p>
                    <p className="text-sm text-gray-500 mt-2">The total number of registered users on the platform.</p>
                </div>
                <div className="text-center">
                    <h3 className="text-gray-800 text-4xl font-extrabold">${counter}<span className="text-blue-600">K</span></h3>
                    <p className="text-base font-bold mt-4">Revenue</p>
                    <p className="text-sm text-gray-500 mt-2">The total revenue generated by the application.</p>
                </div>
                <div className="text-center">
                    <h3 className="text-gray-800 text-4xl font-extrabold">{counter}<span className="text-blue-600">K</span></h3>
                    <p className="text-base font-bold mt-4">Engagement</p>
                    <p className="text-sm text-gray-500 mt-2">The level of user engagement with the application's content and features.</p>
                </div>
                <div className="text-center">
                    <h3 className="text-gray-800 text-4xl font-extrabold">{counter}<span className="text-blue-600">%</span></h3>
                    <p className="text-base font-bold mt-4">Server Uptime</p>
                    <p className="text-sm text-gray-500 mt-2">The percentage of time the server has been operational and available.</p>
                </div>
            </div>
        </div>
    );
}

export default Counts;